version: "3"
services:
  insta-bot:
    build:
      context: .
      dockerfile: cicd/dockerfiles/insta-bot.Dockerfile
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_PASS: "${REDIS_PASS}"
      REDIS_CONVERSATION_TTL: "${REDIS_CONVERSATION_TTL}"
      REDIS_HISTORY_MESSAGES_TTL: "${REDIS_HISTORY_MESSAGES_TTL}"
      GOOGLE_CREDENTIALS: "${GOOGLE_CREDENTIALS}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_GPT_MODEL_FOR_CONV: "${OPENAI_GPT_MODEL_FOR_CONV}"
      OPENAI_GPT_MODEL_FOR_HISTORY: "${OPENAI_GPT_MODEL_FOR_HISTORY}"
      BOT_TOKEN: "${BOT_TOKEN}"
      BOT_CREATOR_USER_ID: "${BOT_CREATOR_USER_ID}"
      BOT_UPDATES_TIMEOUT: "${BOT_UPDATES_TIMEOUT}"
      CAPTION_CHARS_LIMIT: "${CAPTION_CHARS_LIMIT}"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --requirepass "${REDIS_PASS}"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: