version: "3"
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass zakEfron1
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=zakEfron1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: