version: "3"

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass zakEfron1
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=zakEfron1
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data

  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    depends_on:
      - redis
      - instloader
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
      - LOG_LEVEL=DEBUG
      - METRICS_SERVER_ADDR=:9091

  instloader:
    build:
      context: .
      dockerfile: docker/instloader.Dockerfile
    env_file:
      - .env
    environment:
      - INSTAGRAM_SESSION_FILE=/data/session.json
    ports:
      - "8003:8003"
    volumes:
      - instloader-data:/data

volumes:
  redis-data:
  instloader-data:
