/*
instagrapi-rest

RESTful API Service for instagrapi

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instapi

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"os"
)


// VideoApiService VideoApi service
type VideoApiService service

type ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest struct {
	ctx context.Context
	ApiService *VideoApiService
	sessionid *string
	url *string
	filename *string
	folder *string
	returnFile *bool
}

func (r ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest) Sessionid(sessionid string) ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest {
	r.sessionid = &sessionid
	return r
}

func (r ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest) Url(url string) ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest {
	r.url = &url
	return r
}

func (r ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest) Filename(filename string) ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest {
	r.filename = &filename
	return r
}

func (r ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest) Folder(folder string) ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest {
	r.folder = &folder
	return r
}

func (r ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest) ReturnFile(returnFile bool) ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest {
	r.returnFile = &returnFile
	return r
}

func (r ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.VideoDownloadByUrlVideoDownloadByUrlPostExecute(r)
}

/*
VideoDownloadByUrlVideoDownloadByUrlPost Video Download By Url

Download video using URL
    

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest
*/
func (a *VideoApiService) VideoDownloadByUrlVideoDownloadByUrlPost(ctx context.Context) ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest {
	return ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *VideoApiService) VideoDownloadByUrlVideoDownloadByUrlPostExecute(r ApiVideoDownloadByUrlVideoDownloadByUrlPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoApiService.VideoDownloadByUrlVideoDownloadByUrlPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/video/download/by_url"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.sessionid == nil {
		return localVarReturnValue, nil, reportError("sessionid is required and must be specified")
	}
	if r.url == nil {
		return localVarReturnValue, nil, reportError("url is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarFormParams.Add("sessionid", parameterToString(*r.sessionid, ""))
	localVarFormParams.Add("url", parameterToString(*r.url, ""))
	if r.filename != nil {
		localVarFormParams.Add("filename", parameterToString(*r.filename, ""))
	}
	if r.folder != nil {
		localVarFormParams.Add("folder", parameterToString(*r.folder, ""))
	}
	if r.returnFile != nil {
		localVarFormParams.Add("returnFile", parameterToString(*r.returnFile, ""))
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiVideoDownloadVideoDownloadPostRequest struct {
	ctx context.Context
	ApiService *VideoApiService
	sessionid *string
	mediaPk *int32
	folder *string
	returnFile *bool
}

func (r ApiVideoDownloadVideoDownloadPostRequest) Sessionid(sessionid string) ApiVideoDownloadVideoDownloadPostRequest {
	r.sessionid = &sessionid
	return r
}

func (r ApiVideoDownloadVideoDownloadPostRequest) MediaPk(mediaPk int32) ApiVideoDownloadVideoDownloadPostRequest {
	r.mediaPk = &mediaPk
	return r
}

func (r ApiVideoDownloadVideoDownloadPostRequest) Folder(folder string) ApiVideoDownloadVideoDownloadPostRequest {
	r.folder = &folder
	return r
}

func (r ApiVideoDownloadVideoDownloadPostRequest) ReturnFile(returnFile bool) ApiVideoDownloadVideoDownloadPostRequest {
	r.returnFile = &returnFile
	return r
}

func (r ApiVideoDownloadVideoDownloadPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.VideoDownloadVideoDownloadPostExecute(r)
}

/*
VideoDownloadVideoDownloadPost Video Download

Download video using media pk
    

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiVideoDownloadVideoDownloadPostRequest
*/
func (a *VideoApiService) VideoDownloadVideoDownloadPost(ctx context.Context) ApiVideoDownloadVideoDownloadPostRequest {
	return ApiVideoDownloadVideoDownloadPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *VideoApiService) VideoDownloadVideoDownloadPostExecute(r ApiVideoDownloadVideoDownloadPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoApiService.VideoDownloadVideoDownloadPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/video/download"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.sessionid == nil {
		return localVarReturnValue, nil, reportError("sessionid is required and must be specified")
	}
	if r.mediaPk == nil {
		return localVarReturnValue, nil, reportError("mediaPk is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarFormParams.Add("sessionid", parameterToString(*r.sessionid, ""))
	localVarFormParams.Add("media_pk", parameterToString(*r.mediaPk, ""))
	if r.folder != nil {
		localVarFormParams.Add("folder", parameterToString(*r.folder, ""))
	}
	if r.returnFile != nil {
		localVarFormParams.Add("returnFile", parameterToString(*r.returnFile, ""))
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest struct {
	ctx context.Context
	ApiService *VideoApiService
	sessionid *string
	url *string
	caption *string
	mentions *[]StoryMention
	locations *[]StoryLocation
	links *[]StoryLink
	hashtags *[]StoryHashtag
	stickers *[]StorySticker
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Sessionid(sessionid string) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	r.sessionid = &sessionid
	return r
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Url(url string) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	r.url = &url
	return r
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Caption(caption string) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	r.caption = &caption
	return r
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Mentions(mentions []StoryMention) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	r.mentions = &mentions
	return r
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Locations(locations []StoryLocation) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	r.locations = &locations
	return r
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Links(links []StoryLink) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	r.links = &links
	return r
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Hashtags(hashtags []StoryHashtag) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	r.hashtags = &hashtags
	return r
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Stickers(stickers []StorySticker) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	r.stickers = &stickers
	return r
}

func (r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) Execute() (*Story, *http.Response, error) {
	return r.ApiService.VideoUploadToStoryByUrlVideoUploadToStoryByUrlPostExecute(r)
}

/*
VideoUploadToStoryByUrlVideoUploadToStoryByUrlPost Video Upload To Story By Url

Upload video to story by URL to file
    

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest
*/
func (a *VideoApiService) VideoUploadToStoryByUrlVideoUploadToStoryByUrlPost(ctx context.Context) ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest {
	return ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Story
func (a *VideoApiService) VideoUploadToStoryByUrlVideoUploadToStoryByUrlPostExecute(r ApiVideoUploadToStoryByUrlVideoUploadToStoryByUrlPostRequest) (*Story, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Story
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoApiService.VideoUploadToStoryByUrlVideoUploadToStoryByUrlPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/video/upload_to_story/by_url"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.sessionid == nil {
		return localVarReturnValue, nil, reportError("sessionid is required and must be specified")
	}
	if r.url == nil {
		return localVarReturnValue, nil, reportError("url is required and must be specified")
	}
	if strlen(*r.url) < 1 {
		return localVarReturnValue, nil, reportError("url must have at least 1 elements")
	}
	if strlen(*r.url) > 2083 {
		return localVarReturnValue, nil, reportError("url must have less than 2083 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarFormParams.Add("sessionid", parameterToString(*r.sessionid, ""))
	localVarFormParams.Add("url", parameterToString(*r.url, ""))
	if r.caption != nil {
		localVarFormParams.Add("caption", parameterToString(*r.caption, ""))
	}
	if r.mentions != nil {
		localVarFormParams.Add("mentions", parameterToString(*r.mentions, "csv"))
	}
	if r.locations != nil {
		localVarFormParams.Add("locations", parameterToString(*r.locations, "csv"))
	}
	if r.links != nil {
		localVarFormParams.Add("links", parameterToString(*r.links, "csv"))
	}
	if r.hashtags != nil {
		localVarFormParams.Add("hashtags", parameterToString(*r.hashtags, "csv"))
	}
	if r.stickers != nil {
		localVarFormParams.Add("stickers", parameterToString(*r.stickers, "csv"))
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiVideoUploadToStoryVideoUploadToStoryPostRequest struct {
	ctx context.Context
	ApiService *VideoApiService
	sessionid *string
	file **os.File
	caption *string
	mentions *[]StoryMention
	locations *[]StoryLocation
	links *[]StoryLink
	hashtags *[]StoryHashtag
	stickers *[]StorySticker
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) Sessionid(sessionid string) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	r.sessionid = &sessionid
	return r
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) File(file *os.File) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	r.file = &file
	return r
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) Caption(caption string) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	r.caption = &caption
	return r
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) Mentions(mentions []StoryMention) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	r.mentions = &mentions
	return r
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) Locations(locations []StoryLocation) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	r.locations = &locations
	return r
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) Links(links []StoryLink) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	r.links = &links
	return r
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) Hashtags(hashtags []StoryHashtag) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	r.hashtags = &hashtags
	return r
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) Stickers(stickers []StorySticker) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	r.stickers = &stickers
	return r
}

func (r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) Execute() (*Story, *http.Response, error) {
	return r.ApiService.VideoUploadToStoryVideoUploadToStoryPostExecute(r)
}

/*
VideoUploadToStoryVideoUploadToStoryPost Video Upload To Story

Upload video to story
    

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiVideoUploadToStoryVideoUploadToStoryPostRequest
*/
func (a *VideoApiService) VideoUploadToStoryVideoUploadToStoryPost(ctx context.Context) ApiVideoUploadToStoryVideoUploadToStoryPostRequest {
	return ApiVideoUploadToStoryVideoUploadToStoryPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Story
func (a *VideoApiService) VideoUploadToStoryVideoUploadToStoryPostExecute(r ApiVideoUploadToStoryVideoUploadToStoryPostRequest) (*Story, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Story
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoApiService.VideoUploadToStoryVideoUploadToStoryPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/video/upload_to_story"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.sessionid == nil {
		return localVarReturnValue, nil, reportError("sessionid is required and must be specified")
	}
	if r.file == nil {
		return localVarReturnValue, nil, reportError("file is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarFormParams.Add("sessionid", parameterToString(*r.sessionid, ""))
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"

	fileLocalVarFile := *r.file
	if fileLocalVarFile != nil {
		fbs, _ := ioutil.ReadAll(fileLocalVarFile)
		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
	}
	formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	if r.caption != nil {
		localVarFormParams.Add("caption", parameterToString(*r.caption, ""))
	}
	if r.mentions != nil {
		localVarFormParams.Add("mentions", parameterToString(*r.mentions, "csv"))
	}
	if r.locations != nil {
		localVarFormParams.Add("locations", parameterToString(*r.locations, "csv"))
	}
	if r.links != nil {
		localVarFormParams.Add("links", parameterToString(*r.links, "csv"))
	}
	if r.hashtags != nil {
		localVarFormParams.Add("hashtags", parameterToString(*r.hashtags, "csv"))
	}
	if r.stickers != nil {
		localVarFormParams.Add("stickers", parameterToString(*r.stickers, "csv"))
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiVideoUploadVideoUploadPostRequest struct {
	ctx context.Context
	ApiService *VideoApiService
	sessionid *string
	file **os.File
	caption *string
	thumbnail **os.File
	usertags *[]Usertag
	location *Location
}

func (r ApiVideoUploadVideoUploadPostRequest) Sessionid(sessionid string) ApiVideoUploadVideoUploadPostRequest {
	r.sessionid = &sessionid
	return r
}

func (r ApiVideoUploadVideoUploadPostRequest) File(file *os.File) ApiVideoUploadVideoUploadPostRequest {
	r.file = &file
	return r
}

func (r ApiVideoUploadVideoUploadPostRequest) Caption(caption string) ApiVideoUploadVideoUploadPostRequest {
	r.caption = &caption
	return r
}

func (r ApiVideoUploadVideoUploadPostRequest) Thumbnail(thumbnail *os.File) ApiVideoUploadVideoUploadPostRequest {
	r.thumbnail = &thumbnail
	return r
}

func (r ApiVideoUploadVideoUploadPostRequest) Usertags(usertags []Usertag) ApiVideoUploadVideoUploadPostRequest {
	r.usertags = &usertags
	return r
}

func (r ApiVideoUploadVideoUploadPostRequest) Location(location Location) ApiVideoUploadVideoUploadPostRequest {
	r.location = &location
	return r
}

func (r ApiVideoUploadVideoUploadPostRequest) Execute() (*Media, *http.Response, error) {
	return r.ApiService.VideoUploadVideoUploadPostExecute(r)
}

/*
VideoUploadVideoUploadPost Video Upload

Upload photo and configure to feed
    

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiVideoUploadVideoUploadPostRequest
*/
func (a *VideoApiService) VideoUploadVideoUploadPost(ctx context.Context) ApiVideoUploadVideoUploadPostRequest {
	return ApiVideoUploadVideoUploadPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Media
func (a *VideoApiService) VideoUploadVideoUploadPostExecute(r ApiVideoUploadVideoUploadPostRequest) (*Media, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Media
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoApiService.VideoUploadVideoUploadPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/video/upload"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.sessionid == nil {
		return localVarReturnValue, nil, reportError("sessionid is required and must be specified")
	}
	if r.file == nil {
		return localVarReturnValue, nil, reportError("file is required and must be specified")
	}
	if r.caption == nil {
		return localVarReturnValue, nil, reportError("caption is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarFormParams.Add("sessionid", parameterToString(*r.sessionid, ""))
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"

	fileLocalVarFile := *r.file
	if fileLocalVarFile != nil {
		fbs, _ := ioutil.ReadAll(fileLocalVarFile)
		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
	}
	formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	localVarFormParams.Add("caption", parameterToString(*r.caption, ""))
	var thumbnailLocalVarFormFileName string
	var thumbnailLocalVarFileName     string
	var thumbnailLocalVarFileBytes    []byte

	thumbnailLocalVarFormFileName = "thumbnail"

	var thumbnailLocalVarFile *os.File
	if r.thumbnail != nil {
		thumbnailLocalVarFile = *r.thumbnail
	}
	if thumbnailLocalVarFile != nil {
		fbs, _ := ioutil.ReadAll(thumbnailLocalVarFile)
		thumbnailLocalVarFileBytes = fbs
		thumbnailLocalVarFileName = thumbnailLocalVarFile.Name()
		thumbnailLocalVarFile.Close()
	}
	formFiles = append(formFiles, formFile{fileBytes: thumbnailLocalVarFileBytes, fileName: thumbnailLocalVarFileName, formFileName: thumbnailLocalVarFormFileName})
	if r.usertags != nil {
		localVarFormParams.Add("usertags", parameterToString(*r.usertags, "csv"))
	}
	if r.location != nil {
		paramJson, err := parameterToJson(*r.location)
		if err != nil {
			return localVarReturnValue, nil, err
		}
		localVarFormParams.Add("location", paramJson)
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
