/*
instagrapi-rest

RESTful API Service for instagrapi

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instapi

import (
	"encoding/json"
)

// StoryLink struct for StoryLink
type StoryLink struct {
	WebUri string `json:"webUri"`
	X *float32 `json:"x,omitempty"`
	Y *float32 `json:"y,omitempty"`
	Z *float32 `json:"z,omitempty"`
	Width *float32 `json:"width,omitempty"`
	Height *float32 `json:"height,omitempty"`
	Rotation *float32 `json:"rotation,omitempty"`
}

// NewStoryLink instantiates a new StoryLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoryLink(webUri string) *StoryLink {
	this := StoryLink{}
	this.WebUri = webUri
	var x float32 = 0.5126011
	this.X = &x
	var y float32 = 0.5168225
	this.Y = &y
	var z float32 = 0.0
	this.Z = &z
	var width float32 = 0.50998676
	this.Width = &width
	var height float32 = 0.25875
	this.Height = &height
	var rotation float32 = 0.0
	this.Rotation = &rotation
	return &this
}

// NewStoryLinkWithDefaults instantiates a new StoryLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoryLinkWithDefaults() *StoryLink {
	this := StoryLink{}
	var x float32 = 0.5126011
	this.X = &x
	var y float32 = 0.5168225
	this.Y = &y
	var z float32 = 0.0
	this.Z = &z
	var width float32 = 0.50998676
	this.Width = &width
	var height float32 = 0.25875
	this.Height = &height
	var rotation float32 = 0.0
	this.Rotation = &rotation
	return &this
}

// GetWebUri returns the WebUri field value
func (o *StoryLink) GetWebUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebUri
}

// GetWebUriOk returns a tuple with the WebUri field value
// and a boolean to check if the value has been set.
func (o *StoryLink) GetWebUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebUri, true
}

// SetWebUri sets field value
func (o *StoryLink) SetWebUri(v string) {
	o.WebUri = v
}

// GetX returns the X field value if set, zero value otherwise.
func (o *StoryLink) GetX() float32 {
	if o == nil || o.X == nil {
		var ret float32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryLink) GetXOk() (*float32, bool) {
	if o == nil || o.X == nil {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *StoryLink) HasX() bool {
	if o != nil && o.X != nil {
		return true
	}

	return false
}

// SetX gets a reference to the given float32 and assigns it to the X field.
func (o *StoryLink) SetX(v float32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *StoryLink) GetY() float32 {
	if o == nil || o.Y == nil {
		var ret float32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryLink) GetYOk() (*float32, bool) {
	if o == nil || o.Y == nil {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *StoryLink) HasY() bool {
	if o != nil && o.Y != nil {
		return true
	}

	return false
}

// SetY gets a reference to the given float32 and assigns it to the Y field.
func (o *StoryLink) SetY(v float32) {
	o.Y = &v
}

// GetZ returns the Z field value if set, zero value otherwise.
func (o *StoryLink) GetZ() float32 {
	if o == nil || o.Z == nil {
		var ret float32
		return ret
	}
	return *o.Z
}

// GetZOk returns a tuple with the Z field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryLink) GetZOk() (*float32, bool) {
	if o == nil || o.Z == nil {
		return nil, false
	}
	return o.Z, true
}

// HasZ returns a boolean if a field has been set.
func (o *StoryLink) HasZ() bool {
	if o != nil && o.Z != nil {
		return true
	}

	return false
}

// SetZ gets a reference to the given float32 and assigns it to the Z field.
func (o *StoryLink) SetZ(v float32) {
	o.Z = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *StoryLink) GetWidth() float32 {
	if o == nil || o.Width == nil {
		var ret float32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryLink) GetWidthOk() (*float32, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *StoryLink) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given float32 and assigns it to the Width field.
func (o *StoryLink) SetWidth(v float32) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *StoryLink) GetHeight() float32 {
	if o == nil || o.Height == nil {
		var ret float32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryLink) GetHeightOk() (*float32, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *StoryLink) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given float32 and assigns it to the Height field.
func (o *StoryLink) SetHeight(v float32) {
	o.Height = &v
}

// GetRotation returns the Rotation field value if set, zero value otherwise.
func (o *StoryLink) GetRotation() float32 {
	if o == nil || o.Rotation == nil {
		var ret float32
		return ret
	}
	return *o.Rotation
}

// GetRotationOk returns a tuple with the Rotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryLink) GetRotationOk() (*float32, bool) {
	if o == nil || o.Rotation == nil {
		return nil, false
	}
	return o.Rotation, true
}

// HasRotation returns a boolean if a field has been set.
func (o *StoryLink) HasRotation() bool {
	if o != nil && o.Rotation != nil {
		return true
	}

	return false
}

// SetRotation gets a reference to the given float32 and assigns it to the Rotation field.
func (o *StoryLink) SetRotation(v float32) {
	o.Rotation = &v
}

func (o StoryLink) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["webUri"] = o.WebUri
	}
	if o.X != nil {
		toSerialize["x"] = o.X
	}
	if o.Y != nil {
		toSerialize["y"] = o.Y
	}
	if o.Z != nil {
		toSerialize["z"] = o.Z
	}
	if o.Width != nil {
		toSerialize["width"] = o.Width
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.Rotation != nil {
		toSerialize["rotation"] = o.Rotation
	}
	return json.Marshal(toSerialize)
}

type NullableStoryLink struct {
	value *StoryLink
	isSet bool
}

func (v NullableStoryLink) Get() *StoryLink {
	return v.value
}

func (v *NullableStoryLink) Set(val *StoryLink) {
	v.value = val
	v.isSet = true
}

func (v NullableStoryLink) IsSet() bool {
	return v.isSet
}

func (v *NullableStoryLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoryLink(val *StoryLink) *NullableStoryLink {
	return &NullableStoryLink{value: val, isSet: true}
}

func (v NullableStoryLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoryLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


